### ISSUE TITLE
Use the original liche repository

### ISSUE THREAD

**Issue by dmitry-at-hyla** [3scale-ops/tf-vault-secret#10]
Now [Makefile](/3scale-ops/tf-vault-secret/blob/main/Makefile#L7-L11) uses liche fork `dmitry-at-hyla/liche`. This fork has been created just to address issue [#25](https://github.com/raviqqe/liche/issues/25) from the original repository. Right now it is already fixed and merged in PR [#38](https://github.com/raviqqe/liche/pull/38). There is no reason to continue using this fork, please switch to the original repository (just replace `dmitry-at-hyla` with `raviqqe`).

P.S. BTW liche is deprecated now, consider using [muffet](https://github.com/raviqqe/muffet) instead.

**Comment by raelga** [comment]
Thanks for the heads up. :)
